#!/bin/bash
# Manuel hesap ekleme kılavuzu

echo "=== MiniMax Hesap Manuel Ekleme Kılavuzu ==="
echo ""
echo "Tüm temp mail servisleri MiniMax tarafından engellenmiş durumda."
echo "Çözüm: Gerçek email ile kayıt yapıp bilgileri config.json'a ekleyin."
echo ""
echo "ADIMLAR:"
echo ""
echo "1. Tarayıcıda https://account.minimax.io/unified-login adresine gidin"
echo ""
echo "2. Gerçek bir email (Gmail, Outlook, etc.) ile kayıt yapın:"
echo "   - Email girin"
echo "   - Continue'ya tıklayın"
echo "   - OTP kodunu email'den alın"
echo "   - Şifre belirleyin (örn: Mm\$(openssl rand -hex 8)!7 formatında)"
echo ""
echo "3. Kayıt tamamlandıktan sonra tarayıcı console'da şunu çalıştırın:"
echo "   document.cookie"
echo ""
echo "4. Çıktıyı kopyalayın ve aşağıdaki komutu çalıştırın:"
echo ""
echo "   python3 << 'EOF'"
echo "import json"
echo ""
echo "config_path = '/opt/minimax2api/minimax2api/config.json'"
echo "with open(config_path, 'r') as f:"
echo "    config = json.load(f)"
echo ""
echo "# Yeni hesap ekle"
echo "new_account = {"
echo "    'name': 'hesap5',  # veya başka bir isim"
echo "    'email': 'BURAYA_EMAILI_YAZI',  # kaydolduğunuz email"
echo "    'password': 'BURAYA_SIFREYI_YAZI',  # belirlediğiniz şifre"
echo "    'auth_mode': 'token',"
echo "    'base_url': 'https://agent.minimax.io',"
echo "    'is_active': True,"
echo "    'depleted': False"
echo "}"
echo ""
echo "config['accounts'].append(new_account)"
echo ""
echo "with open(config_path, 'w') as f:"
echo "    json.dump(config, f, indent=2)"
echo ""
echo "print('✓ Hesap eklendi')"
echo "EOF"
echo ""
echo "5. Servisi yeniden başlatın:"
echo "   systemctl restart minimax2api"
echo ""
echo "VEYA: 10-20 hesap toplu kayıt için register_oauth.js kullanın:"
echo "   node register_oauth.js google 10"
echo "   (Her hesap için tarayıcıda Google ile giriş yapmanız gerekecek)"
