import { createContext, useContext, useState, ReactNode } from "react"

type Lang = "en" | "cn" | "tr"

const en = {
  nav: {
    dashboard: "Dashboard",
    accounts: "Accounts",
    generator: "Generator",
    apiKeys: "API Keys",
    test: "Test",
    settings: "Settings",
    subtitle: "Proxy Gateway",
  },
  dashboard: {
    title: "Status",
    subtitle: "MiniMax proxy global status overview (auto-refresh every 5s).",
    availableAccounts: "Available Accounts",
    totalRequests: "Total Requests",
    totalTokens: "Total Tokens",
    availableModels: "Available Models",
    cumulative: "Cumulative",
    tokenUsage: "Token usage",
    autoDiscovered: "Auto discovered",
    total: "total",
    accountDetails: "Account Details",
    name: "Name",
    status: "Status",
    requests: "Requests",
    lastUsed: "Last Used",
    authMode: "Auth Mode",
    never: "Never",
    normal: "Active",
    cooling: "Cooling",
    disabled: "Disabled",
    apiEndpoints: "API Endpoints",
    healthCheck: "Health Check",
    sessionDaemon: "Session Daemon",
    pool: "Pool",
    sessionsReady: "sessions ready",
    browsersOpen: "browsers open",
    chromiumRam: "Chromium RAM",
    system: "System",
    requestActivity: "Request Activity",
    lastPolls: "Last 24 polls (5s each)",
    availableModelsTitle: "Available Models",
    active: "Active",
  },
  accounts: {
    title: "Accounts",
    subtitle: "Manage your MiniMax account pool.",
    refresh: "Refresh",
    import: "Import",
    export: "Export",
    autoGenerate: "Auto Generate",
    addAccount: "Add Account",
    total: "Total",
    active: "Active",
    cooldown: "Cooldown",
    disabled: "Disabled",
    addManually: "Add Account Manually",
    nameOptional: "Name (optional)",
    accountName: "Account name",
    authMode: "Auth Mode",
    apiKeyMode: "API Key",
    tokenMode: "Web Token",
    apiKey: "API Key",
    token: "Token",
    bearerToken: "Bearer token value",
    authToken: "Auth Token",
    sameAsAbove: "Same as above",
    baseUrl: "Base URL",
    add: "Add",
    cancel: "Cancel",
    filter: "Filter:",
    all: "All",
    accountList: "Account List",
    noAccounts: "No accounts found.",
    addOne: "Add one",
    orAutoGenerate: "or auto-generate",
    num: "#",
    name: "Name",
    status: "Status",
    auth: "Auth",
    lastUsed: "Last Used",
    actions: "Actions",
    never: "Never",
    test: "Test",
    enable: "Enable",
    disable: "Disable",
  },
  generator: {
    title: "Account Generator",
    subtitle: "Automatically register MiniMax accounts using temporary emails.",
    settings: "Generation Settings",
    numAccounts: "Count",
    parallel: "Parallel",
    start: "Generate",
    stop: "Stop",
    clear: "Clear",
    export: "Export",
    progress: "Progress:",
    success: "Success:",
    failed: "Failed:",
    liveLog: "Log",
    waiting: "Waiting...",
    generatedAccounts: "Generated Accounts",
    noAccounts: "No accounts yet.",
    num: "#",
    email: "Email",
    status: "Status",
    token: "Token",
    selectAll: "Select all",
    addToDaemon: "Add to Daemon",
    daemonTitle: "Session Daemon (Puppeteer)",
    targetSessions: "Target sessions",
    sessionsPerAccount: "sessions/account",
    estimatedRam: "est.",
    start2: "Start",
    stop2: "Stop",
    daemonAccounts: "Daemon Accounts",
    emptyAccounts: "accounts.json is empty",
    inDaemon: "● In Daemon",
    inactive: "○ Inactive",
    sessions: "sessions",
    daemonLog: "Daemon Log",
    noLog: "No logs",
    running: "Running",
    stopped: "Stopped",
    pool: "Pool",
    chromium: "Chromium",
    system: "System",
  },
  tokens: {
    title: "API Key Distribution",
    subtitle: "Manage downstream credentials for this gateway.",
    refresh: "Refresh",
    generateNew: "Generate New Key",
    addManually: "Add Key Manually",
    enterKey: "Enter new proxy Key (e.g. sk-my-key)",
    addBtn: "Add",
    keyList: "Key List",
    noKeys: "No API Keys",
    num: "#",
    apiKey: "API Key",
    actions: "Actions",
  },
  settings: {
    title: "System Settings",
    subtitle: "Manage console authentication and gateway configuration.",
    refreshConfig: "Refresh Config",
    sessionKey: "Current Session Key",
    sessionKeyDesc: "The WebUI uses this key for management operations (stored in browser).",
    sessionKeyPlaceholder: "sk-minimax or other proxy key",
    save: "Save",
    clear: "Clear",
    connectionInfo: "Connection Info",
    apiBaseUrl: "API Base URL",
    minimaxConfig: "MiniMax Configuration",
    minimaxConfigDesc: "Gateway settings.",
    version: "System Version",
    defaultApiKey: "Default API Key",
    baseUrl: "Base URL",
    defaultModel: "Default Model",
    registrationProxy: "Registration Proxy",
    registrationProxyDesc: "Optional HTTP proxy for account registration",
    saveConfig: "Save Config",
    modelAliases: "Model Aliases",
    modelAliasesDesc: "Downstream model names are auto-routed to MiniMax models. JSON format.",
    saveAliases: "Save Aliases",
    usageExample: "Usage Example",
  },
  testPage: {
    title: "API Test",
    subtitle: "Send a chat request to this proxy and view the raw response.",
    refreshModels: "Refresh Models",
    model: "Model",
    messageContent: "Message Content",
    messagePlaceholder: "Enter test message...",
    send: "Send",
    requestMessage: "Request",
    response: "Response",
    responsePlaceholder: "Response will appear here...",
  },
  common: {
    tokenAuth: "Token",
    apiKeyAuth: "API Key",
    statusNormal: "Active",
    statusCooling: "Cooldown",
    statusDisabled: "Disabled",
  },
}

const cn: typeof en = {
  nav: {
    dashboard: "运行状态",
    accounts: "账号管理",
    generator: "自动注册",
    apiKeys: "API Key",
    test: "接口测试",
    settings: "系统设置",
    subtitle: "代理网关",
  },
  dashboard: {
    title: "运行状态",
    subtitle: "MiniMax 代理全局状态概览（每 5 秒自动刷新）。",
    availableAccounts: "可用账号",
    totalRequests: "总请求数",
    totalTokens: "总 Tokens",
    availableModels: "可用模型",
    cumulative: "累计",
    tokenUsage: "累计消耗",
    autoDiscovered: "自动发现",
    total: "共",
    accountDetails: "账号详情",
    name: "名称",
    status: "状态",
    requests: "请求数",
    lastUsed: "最后使用",
    authMode: "认证方式",
    never: "从未",
    normal: "活跃",
    cooling: "冷却中",
    disabled: "已禁用",
    apiEndpoints: "API 接口",
    healthCheck: "健康检查",
    sessionDaemon: "Session Daemon",
    pool: "池",
    sessionsReady: "个 session 就绪",
    browsersOpen: "个浏览器运行",
    chromiumRam: "Chromium 内存",
    system: "系统",
    requestActivity: "请求活动",
    lastPolls: "最近 24 次轮询（每 5 秒）",
    availableModelsTitle: "可用模型",
    active: "活跃",
  },
  accounts: {
    title: "账号管理",
    subtitle: "统一管理上游 MiniMax 账号池。",
    refresh: "刷新",
    import: "导入",
    export: "导出",
    autoGenerate: "自动注册",
    addAccount: "添加账号",
    total: "总计",
    active: "可用",
    cooldown: "冷却中",
    disabled: "已禁用",
    addManually: "手动添加账号",
    nameOptional: "名称（选填）",
    accountName: "账号名称",
    authMode: "认证方式",
    apiKeyMode: "API Key",
    tokenMode: "网页 Token",
    apiKey: "API Key",
    token: "Token",
    bearerToken: "localStorage._token 的值",
    authToken: "Token 确认",
    sameAsAbove: "同上",
    baseUrl: "Base URL",
    add: "添加",
    cancel: "取消",
    filter: "筛选：",
    all: "全部",
    accountList: "账号列表",
    noAccounts: "暂无账号。",
    addOne: "手动添加",
    orAutoGenerate: "或自动注册",
    num: "#",
    name: "名称",
    status: "状态",
    auth: "认证",
    lastUsed: "最后使用",
    actions: "操作",
    never: "从未",
    test: "测试",
    enable: "启用",
    disable: "禁用",
  },
  generator: {
    title: "自动注册",
    subtitle: "使用临时邮箱自动批量注册 MiniMax 账号。",
    settings: "注册设置",
    numAccounts: "数量",
    parallel: "并行",
    start: "开始注册",
    stop: "停止",
    clear: "清空",
    export: "导出",
    progress: "进度：",
    success: "成功：",
    failed: "失败：",
    liveLog: "实时日志",
    waiting: "等待中...",
    generatedAccounts: "已注册账号",
    noAccounts: "尚未注册任何账号。",
    num: "#",
    email: "邮箱",
    status: "状态",
    token: "Token",
    selectAll: "全选",
    addToDaemon: "加入 Daemon",
    daemonTitle: "Session Daemon (Puppeteer)",
    targetSessions: "目标 Session 数",
    sessionsPerAccount: "个/账号",
    estimatedRam: "预估",
    start2: "启动",
    stop2: "停止",
    daemonAccounts: "Daemon 账号",
    emptyAccounts: "accounts.json 为空",
    inDaemon: "● 运行中",
    inactive: "○ 未激活",
    sessions: "个 session",
    daemonLog: "Daemon 日志",
    noLog: "暂无日志",
    running: "运行中",
    stopped: "已停止",
    pool: "池",
    chromium: "Chromium",
    system: "系统",
  },
  tokens: {
    title: "API Key 分发",
    subtitle: "管理可以访问此网关的下游凭证。",
    refresh: "刷新",
    generateNew: "生成新 Key",
    addManually: "手动添加 Key",
    enterKey: "输入新的代理 Key（如 sk-my-key）",
    addBtn: "添加",
    keyList: "Key 列表",
    noKeys: "暂无 API Key",
    num: "#",
    apiKey: "API Key",
    actions: "操作",
  },
  settings: {
    title: "系统设置",
    subtitle: "管理控制台认证与网关配置。",
    refreshConfig: "刷新配置",
    sessionKey: "当前会话 Key",
    sessionKeyDesc: "WebUI 使用此 Key 进行管理操作（保存在浏览器本地）。",
    sessionKeyPlaceholder: "sk-minimax 或其他代理 Key",
    save: "保存",
    clear: "清除",
    connectionInfo: "连接信息",
    apiBaseUrl: "API 基础地址",
    minimaxConfig: "MiniMax 配置",
    minimaxConfigDesc: "网关设置。",
    version: "系统版本",
    defaultApiKey: "默认 API Key",
    baseUrl: "Base URL",
    defaultModel: "默认模型",
    registrationProxy: "注册代理",
    registrationProxyDesc: "账号注册用 HTTP 代理（可选）",
    saveConfig: "保存配置",
    modelAliases: "模型映射规则",
    modelAliasesDesc: "下游传入的模型名称自动路由至 MiniMax 实际模型。JSON 格式。",
    saveAliases: "保存映射",
    usageExample: "使用示例",
  },
  testPage: {
    title: "接口测试",
    subtitle: "向本代理发送对话请求并查看原始响应。",
    refreshModels: "刷新模型",
    model: "模型",
    messageContent: "消息内容",
    messagePlaceholder: "输入测试消息...",
    send: "发送",
    requestMessage: "请求消息",
    response: "响应",
    responsePlaceholder: "响应将显示在此处...",
  },
  common: {
    tokenAuth: "Token",
    apiKeyAuth: "API Key",
    statusNormal: "正常",
    statusCooling: "冷却中",
    statusDisabled: "已禁用",
  },
}

const tr: typeof en = {
  nav: {
    dashboard: "Durum",
    accounts: "Hesaplar",
    generator: "Üretici",
    apiKeys: "API Anahtarları",
    test: "Test",
    settings: "Ayarlar",
    subtitle: "Proxy Ağ Geçidi",
  },
  dashboard: {
    title: "Durum",
    subtitle: "MiniMax proxy genel durum özeti (5 saniyede bir güncellenir).",
    availableAccounts: "Kullanılabilir Hesaplar",
    totalRequests: "Toplam İstek",
    totalTokens: "Toplam Token",
    availableModels: "Kullanılabilir Modeller",
    cumulative: "Kümülatif",
    tokenUsage: "Token kullanımı",
    autoDiscovered: "Otomatik keşfedildi",
    total: "toplam",
    accountDetails: "Hesap Detayları",
    name: "İsim",
    status: "Durum",
    requests: "İstekler",
    lastUsed: "Son Kullanım",
    authMode: "Kimlik Doğrulama",
    never: "Hiç",
    normal: "Aktif",
    cooling: "Soğuyor",
    disabled: "Devre Dışı",
    apiEndpoints: "API Uç Noktaları",
    healthCheck: "Sağlık Kontrolü",
    sessionDaemon: "Oturum Daemon'ı",
    pool: "Havuz",
    sessionsReady: "oturum hazır",
    browsersOpen: "tarayıcı açık",
    chromiumRam: "Chromium RAM",
    system: "Sistem",
    requestActivity: "İstek Aktivitesi",
    lastPolls: "Son 24 anket (5s arayla)",
    availableModelsTitle: "Kullanılabilir Modeller",
    active: "Aktif",
  },
  accounts: {
    title: "Hesaplar",
    subtitle: "MiniMax hesap havuzunuzu yönetin.",
    refresh: "Yenile",
    import: "İçe Aktar",
    export: "Dışa Aktar",
    autoGenerate: "Otomatik Oluştur",
    addAccount: "Hesap Ekle",
    total: "Toplam",
    active: "Aktif",
    cooldown: "Soğuma",
    disabled: "Devre Dışı",
    addManually: "Manuel Hesap Ekle",
    nameOptional: "İsim (opsiyonel)",
    accountName: "Hesap adı",
    authMode: "Kimlik Doğrulama",
    apiKeyMode: "API Key",
    tokenMode: "Web Token",
    apiKey: "API Key",
    token: "Token",
    bearerToken: "Bearer token değeri",
    authToken: "Auth Token",
    sameAsAbove: "Yukarıdakiyle aynı",
    baseUrl: "Base URL",
    add: "Ekle",
    cancel: "İptal",
    filter: "Filtre:",
    all: "Tümü",
    accountList: "Hesap Listesi",
    noAccounts: "Hesap bulunamadı.",
    addOne: "Ekle",
    orAutoGenerate: "veya otomatik oluştur",
    num: "#",
    name: "İsim",
    status: "Durum",
    auth: "Kimlik",
    lastUsed: "Son Kullanım",
    actions: "İşlemler",
    never: "Hiç",
    test: "Test",
    enable: "Etkinleştir",
    disable: "Devre Dışı",
  },
  generator: {
    title: "Hesap Üretici",
    subtitle: "Geçici e-postalar kullanarak otomatik MiniMax hesabı oluşturun.",
    settings: "Oluşturma Ayarları",
    numAccounts: "Adet",
    parallel: "Paralel",
    start: "Üret",
    stop: "Durdur",
    clear: "Temizle",
    export: "Dışa Aktar",
    progress: "İlerleme:",
    success: "Başarılı:",
    failed: "Başarısız:",
    liveLog: "Canlı Log",
    waiting: "Bekleniyor...",
    generatedAccounts: "Oluşturulan Hesaplar",
    noAccounts: "Henüz hesap yok.",
    num: "#",
    email: "E-posta",
    status: "Durum",
    token: "Token",
    selectAll: "Tümünü seç",
    addToDaemon: "Daemon'a Ekle",
    daemonTitle: "Session Daemon (Puppeteer)",
    targetSessions: "Hedef session sayısı",
    sessionsPerAccount: "session/hesap",
    estimatedRam: "tahmini",
    start2: "Başlat",
    stop2: "Durdur",
    daemonAccounts: "Daemon Hesapları",
    emptyAccounts: "accounts.json boş",
    inDaemon: "● Daemon'da",
    inactive: "○ Pasif",
    sessions: "session",
    daemonLog: "Daemon Log",
    noLog: "Log yok",
    running: "Çalışıyor",
    stopped: "Durdu",
    pool: "Havuz",
    chromium: "Chromium",
    system: "Sistem",
  },
  tokens: {
    title: "API Key Dağıtımı",
    subtitle: "Bu ağ geçidine erişebilecek istemci kimlik bilgilerini yönetin.",
    refresh: "Yenile",
    generateNew: "Yeni Key Oluştur",
    addManually: "Manuel Key Ekle",
    enterKey: "Yeni proxy Key girin (örn. sk-my-key)",
    addBtn: "Ekle",
    keyList: "Key Listesi",
    noKeys: "API Key yok",
    num: "#",
    apiKey: "API Key",
    actions: "İşlemler",
  },
  settings: {
    title: "Sistem Ayarları",
    subtitle: "Konsol kimlik doğrulamasını ve ağ geçidi yapılandırmasını yönetin.",
    refreshConfig: "Yapılandırmayı Yenile",
    sessionKey: "Mevcut Oturum Anahtarı",
    sessionKeyDesc: "WebUI bu anahtarı yönetim işlemleri için kullanır (tarayıcıda saklanır).",
    sessionKeyPlaceholder: "sk-minimax veya başka bir proxy key",
    save: "Kaydet",
    clear: "Temizle",
    connectionInfo: "Bağlantı Bilgisi",
    apiBaseUrl: "API Temel URL",
    minimaxConfig: "MiniMax Yapılandırması",
    minimaxConfigDesc: "Ağ geçidi ayarları.",
    version: "Sistem Versiyonu",
    defaultApiKey: "Varsayılan API Key",
    baseUrl: "Base URL",
    defaultModel: "Varsayılan Model",
    registrationProxy: "Kayıt Proxy",
    registrationProxyDesc: "Hesap kaydı için HTTP proxy (opsiyonel)",
    saveConfig: "Yapılandırmayı Kaydet",
    modelAliases: "Model Takma Adları",
    modelAliasesDesc: "İstemci model adları otomatik olarak MiniMax modellerine yönlendirilir. JSON formatı.",
    saveAliases: "Takma Adları Kaydet",
    usageExample: "Kullanım Örneği",
  },
  testPage: {
    title: "API Testi",
    subtitle: "Bu proxy'ye sohbet isteği gönderin ve ham yanıtı görüntüleyin.",
    refreshModels: "Modelleri Yenile",
    model: "Model",
    messageContent: "Mesaj İçeriği",
    messagePlaceholder: "Test mesajı girin...",
    send: "Gönder",
    requestMessage: "İstek",
    response: "Yanıt",
    responsePlaceholder: "Yanıt burada görünecek...",
  },
  common: {
    tokenAuth: "Token",
    apiKeyAuth: "API Key",
    statusNormal: "Aktif",
    statusCooling: "Soğuyor",
    statusDisabled: "Devre Dışı",
  },
}

export const translations = { en, cn, tr }

type Translations = typeof en
type LangCtx = { lang: Lang; tr: Translations; setLang: (l: Lang) => void }
const LangContext = createContext<LangCtx>({ lang: "en", tr: en, setLang: () => {} })

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>(() => (localStorage.getItem("lang") as Lang) || "en")
  const changeLang = (l: Lang) => { setLang(l); localStorage.setItem("lang", l) }
  return (
    <LangContext.Provider value={{ lang, tr: translations[lang], setLang: changeLang }}>
      {children}
    </LangContext.Provider>
  )
}

export const useLang = () => useContext(LangContext)
